# Generated by Django 4.2.10 on 2025-03-05 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('travel_style', models.CharField(blank=True, max_length=100, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
                ('accommodation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('transportation', models.CharField(blank=True, max_length=100, null=True)),
                ('health_issues', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='api.userpreference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
