# Generated by Django 4.2.10 on 2025-03-10 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='accommodation_type',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='duration',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='departure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
